name: release-ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  release:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # cache yarn deps
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: prepare
        id: prepare
        shell: bash
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" >> ~/.npmrc
          git config user.name "GitHub Actions Build"
          git config user.email "developers@aave.com"

      - name: install
        id: install
        run: |
          npm ci

      - id: lint
        name: lint
        run: |
          npm run lint

      - id: build
        name: build
        run: |
          npm run build

      - id: prerelease
        name: prerelease
        if: |
          github.event.pull_request.head.repo.full_name == github.repository &&
          !contains(github.head_ref, 'dependabot') &&
          !contains(github.event.head_commit.message, 'chore(release)') &&
          github.ref != 'refs/heads/master'
        run: |
          npm run release --message "chore(release): Release v%s :tada: [ci skip]" --prerelease ${{ github.sha }}
          npm publish --tag canary --access public

      - id: release
        name: release
        if: |
          github.ref == 'refs/heads/master'
        run: |
          npm run release --message "chore(release): Release v%s :tada: [ci skip]"
          git push --follow-tags origin master
          npm publish --access public
